FROM debian-13-base

# Adapted from: https://github.com/theasp/docker-novnc

# Install git, supervisor, VNC, & X11 packages
RUN set -ex; \
    apt-get update; \
    apt-get install -y \
      fluxbox \
      git \
      net-tools \
      novnc \
      supervisor \
      x11vnc \
      xterm \
      xvfb

ENV HOME=/root \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    LC_ALL=C.UTF-8 \
    DISPLAY=:0.0 \
    DISPLAY_WIDTH=1024 \
    DISPLAY_HEIGHT=768 \
    RUN_XTERM=yes \
    RUN_FLUXBOX=yes
COPY ./app /app

EXPOSE 8000/tcp
HEALTHCHECK --start-period=30s CMD /usr/bin/curl -If http://127.0.0.1:8000/vnc.html

CMD ["/app/entrypoint.sh"]
