FROM debian:12-slim

RUN set -xe \
    && apt update \
    && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends nfs-kernel-server systemd iproute2 procps

RUN systemctl mask rpcbind.service rpcbind.socket rpc-statd.service \
    && systemctl enable nfs-kernel-server.service

COPY rootfs/ /

EXPOSE 111/udp 2049/tcp
STOPSIGNAL SIGRTMIN+3

ENTRYPOINT ["/usr/lib/systemd/systemd"]
