FROM debian:13-slim

COPY rootfs/ /

RUN set -xe \
    && apt update \
    && apt full-upgrade -y \
    && apt autoremove \
    && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends bind9-dnsutils ca-certificates curl \
       file iproute2 iputils-ping netcat-traditional procps vim-tiny \
    && update-alternatives --set editor /usr/bin/vim.tiny \
    && ln -s /usr/bin/vim.tiny /usr/local/bin/vim

CMD ["/bin/bash"]
