FROM alpine-3-base

ARG VERSION=v0.18.1
ARG REST_VERSION=v0.14.0

RUN apk add openssh

RUN ubi --project restic/restic --tag $VERSION --in /usr/local/bin
RUN ubi --project restic/rest-server --tag $REST_VERSION --in /usr/local/bin

COPY rootfs/ /

VOLUME ["/etc/restic", "/var/lib/restic"]

ENV RESTIC_CACHE_DIR=/var/lib/restic/cache
