FROM debian:12-slim

COPY rootfs/ /

RUN set -xe \
    && apt update \
    && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends iproute2 iputils-ping netcat-traditional procps vim-tiny \
         bind9-dnsutils ca-certificates curl dante-server \
    && update-alternatives --set editor /usr/bin/vim.tiny

EXPOSE 1080/tcp

ENTRYPOINT ["/usr/sbin/danted"]
