FROM mcr.microsoft.com/playwright:latest

RUN set -xe \
    && /usr/bin/npx playwright install firefox

EXPOSE 8080/tcp

CMD ["/usr/bin/npx", "playwright", "run-server", "--port", "8080", "--path", "/ws"]
