ARG VERSION=1.55.1
FROM mcr.microsoft.com/playwright:v${VERSION}-noble

RUN set -xe \
    && apt update \
    && apt full-upgrade -y \
    && apt autoremove -y \
    && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends bind9-dnsutils ca-certificates curl \
       file iproute2 iputils-ping netcat-traditional procps vim-tiny \
    && update-alternatives --set editor /usr/bin/vim.tiny \
    && update-alternatives --install /usr/bin/vim vim /usr/bin/vim.tiny 1

RUN set -xe \
    && /usr/bin/npx -y playwright@${VERSION} install firefox --with-deps

EXPOSE 8080/tcp

HEALTHCHECK --start-period=30s CMD /usr/bin/curl -f http://127.0.0.1:8080/ws

# FIXME: VERSION should get used here but... everything is dumb.
CMD ["/usr/bin/npx", "playwright@1.55.1", "run-server", "--port", "8080", "--path", "/ws"]
