FROM mcr.microsoft.com/playwright:v1.54.1-noble

RUN set -xe \
    && apt update \
    && apt full-upgrade -y \
    && apt autoremove -y \
    && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends bind9-dnsutils ca-certificates curl \
       file iproute2 iputils-ping netcat-traditional procps vim-tiny \
    && update-alternatives --set editor /usr/bin/vim.tiny \
    && update-alternatives --install /usr/bin/vim vim /usr/bin/vim.tiny 1

RUN set -xe \
    && /usr/bin/npx -y playwright@1.53.2 install firefox --with-deps

EXPOSE 8080/tcp

CMD ["/usr/bin/npx", "playwright@1.53.2", "run-server", "--port", "8080", "--path", "/ws"]
