FROM debian-12-base

ARG TARGETARCH
ARG VERSION=0.22.3

RUN curl -L https://github.com/juanfont/headscale/releases/download/v${VERSION}/headscale_${VERSION}_linux_${TARGETARCH} -o /usr/local/bin/headscale; \
    chmod +x /usr/local/bin/headscale; \
    mkdir -p /etc/headscale /var/lib/headscale /var/run/headscale

VOLUME /data

CMD ["/usr/local/bin/headscale", "serve"]
