FROM debian-13-base

RUN set -xe \
    && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
       ruby

RUN curl https://mise.run/bash | sh

# Required by most Actions
RUN /root/.local/bin/mise use -g node@24 yarn@1.22

RUN /root/.local/bin/mise use -g docker-cli@latest

COPY entrypoint.sh /usr/local/bin/
ENTRYPOINT ["entrypoint.sh"]

CMD [ "node" ]
