FROM debian-13-base

ARG VERSION=v2.6.1

RUN ubi --project rfjakob/gocryptfs --tag $VERSION --in /usr/local/bin

COPY rootfs/ /

VOLUME ["/etc/gocryptfs", "/mnt/crypt", "/mnt/share"]

CMD ["/usr/local/bin/run-gocryptfs", "/mnt/crypt", "/mnt/share"]
