---
name: Build NFS Server

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'nfs/**'
  # Build at noon, on the 1st and 15th of each month.
  schedule:
    - cron: '0 12 1 * *'
    - cron: '0 12 15 * *'

jobs:
  build_nfs:
    uses: ./.github/workflows/build_container.yaml
    with:
      image: nfs
      platforms: '["amd64", "arm64"]'
