---
name: Build NFS Server

on:
  workflow_dispatch: {}

env:
  DOCKER_TAG: 'nfs:${{ github.sha }}'
  DOCKER_TAR: 'nfs_${{ github.sha }}.tar'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build Docker Container
        run: |
          docker build --platform linux/amd64 --tag $DOCKER_TAG -f nfs/Containerfile nfs
      - name: Export Docker Container
        run: |
          docker save -o "$DOCKER_TAR" $DOCKER_TAG
      - uses: actions/upload-artifact@v4
        with:
          name: '${{ env.DOCKER_TAR }}'
          path: '${{ env.DOCKER_TAR }}'
