---
name: Build NFS Server

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'nfs/**'

jobs:
  build_nfs:
    uses: ./.github/workflows/build_container.yaml
    with:
      image: nfs
      platforms: '["amd64", "arm64"]'
