---
name: Build Dante Proxy Server

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'dante/**'
  # Build at noon, on the 1st and 15th of each month.
  schedule:
    - cron: '0 12 1 * *'
    - cron: '0 12 15 * *'

jobs:
  build_dante:
    uses: ./.github/workflows/build_container.yaml
    with:
      image: dante
      platforms: '["amd64", "arm64"]'
